source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'httparty'
gem 'minitest'
gem 'simplecov'
gem 'geodna', git: 'https://github.com/hardlianotion/geodna-ruby.git'
gem 'rack-minitest', git: 'git://github.com/brandonweiss/rack-minitest.git'
gem 'rack-test'
